# Generated by Django 2.2.9 on 2020-08-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('audio', models.FileField(upload_to='original/')),
                ('reversedaudio', models.FileField(blank=True, null=True, upload_to='reversed/')),
            ],
        ),
    ]
