# Generated by Django 3.2 on 2021-07-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='audio',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='sound',
            name='reversedaudio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
