# Generated by Django 3.2 on 2021-07-05 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0002_auto_20210704_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevSound',
            fields=[
                ('og', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sounds.sound')),
                ('reversedaudio', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='sound',
            name='reversedaudio',
        ),
    ]
